services:
  mysql:
    image: mysql:8.0
    container_name: moomoo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: moomoo_trading
      MYSQL_USER: moomoo
      MYSQL_PASSWORD: moomoo123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: moomoo_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 3s
      retries: 5

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: moomoo_api
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=moomoo
      - DB_PASSWORD=moomoo123
      - DB_DATABASE=moomoo_trading
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - PORT=8081
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthz"]
      timeout: 30s
      retries: 3

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: moomoo_web
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET=your-super-secret-key-change-this-in-production
      - NEXT_PUBLIC_API_URL=http://localhost:8081
      - NEXTAUTH_URL_INTERNAL=http://moomoo_web:3001
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001"]
      timeout: 30s
      retries: 3

volumes:
  mysql_data:
  redis_data: